name = "CardGames"
uuid = "a4ce1080-759e-422e-b645-8414b3537eef"
authors = ["Paul Nemec"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
